//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.Printforme;
using CMS.CustomTables;

[assembly: RegisterCustomTable(AlbumPagePhotoItem.CLASS_NAME, typeof(AlbumPagePhotoItem))]

namespace CMS.CustomTables.Types.Printforme
{
	/// <summary>
	/// Represents a content item of type AlbumPagePhotoItem.
	/// </summary>
	public partial class AlbumPagePhotoItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Printforme.AlbumPagePhoto";


		/// <summary>
		/// The instance of the class that provides extended API for working with AlbumPagePhotoItem fields.
		/// </summary>
		private readonly AlbumPagePhotoItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// AlbumPageID.
		/// </summary>
		[DatabaseField]
		public int AlbumPageID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("AlbumPageID"), 0);
			}
			set
			{
				SetValue("AlbumPageID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// PhotoLocation.
		/// </summary>
		[DatabaseField]
		public string PhotoLocation
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PhotoLocation"), @"");
			}
			set
			{
				SetValue("PhotoLocation", value);
			}
		}


		/// <summary>
		/// Sequence.
		/// </summary>
		[DatabaseField]
		public int Sequence
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("Sequence"), 0);
			}
			set
			{
				SetValue("Sequence", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with AlbumPagePhotoItem fields.
		/// </summary>
		[RegisterProperty]
		public AlbumPagePhotoItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with AlbumPagePhotoItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class AlbumPagePhotoItemFields : AbstractHierarchicalObject<AlbumPagePhotoItemFields>
		{
			/// <summary>
			/// The content item of type AlbumPagePhotoItem that is a target of the extended API.
			/// </summary>
			private readonly AlbumPagePhotoItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="AlbumPagePhotoItemFields" /> class with the specified content item of type AlbumPagePhotoItem.
			/// </summary>
			/// <param name="instance">The content item of type AlbumPagePhotoItem that is a target of the extended API.</param>
			public AlbumPagePhotoItemFields(AlbumPagePhotoItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// AlbumPageID.
			/// </summary>
			public int AlbumPageID
			{
				get
				{
					return mInstance.AlbumPageID;
				}
				set
				{
					mInstance.AlbumPageID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}


			/// <summary>
			/// PhotoLocation.
			/// </summary>
			public string PhotoLocation
			{
				get
				{
					return mInstance.PhotoLocation;
				}
				set
				{
					mInstance.PhotoLocation = value;
				}
			}


			/// <summary>
			/// Sequence.
			/// </summary>
			public int Sequence
			{
				get
				{
					return mInstance.Sequence;
				}
				set
				{
					mInstance.Sequence = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="AlbumPagePhotoItem" /> class.
		/// </summary>
		public AlbumPagePhotoItem() : base(CLASS_NAME)
		{
			mFields = new AlbumPagePhotoItemFields(this);
		}

		#endregion
	}
}