//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.Printforme;
using CMS.CustomTables;

[assembly: RegisterCustomTable(AlbumPageItem.CLASS_NAME, typeof(AlbumPageItem))]

namespace CMS.CustomTables.Types.Printforme
{
	/// <summary>
	/// Represents a content item of type AlbumPageItem.
	/// </summary>
	public partial class AlbumPageItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Printforme.AlbumPage";


		/// <summary>
		/// The instance of the class that provides extended API for working with AlbumPageItem fields.
		/// </summary>
		private readonly AlbumPageItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Album ID.
		/// </summary>
		[DatabaseField]
		public int AlbumID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("AlbumID"), 0);
			}
			set
			{
				SetValue("AlbumID", value);
			}
		}


		/// <summary>
		/// Album Page Layout ID.
		/// </summary>
		[DatabaseField]
		public int AlbumPageLayoutID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("AlbumPageLayoutID"), 0);
			}
			set
			{
				SetValue("AlbumPageLayoutID", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with AlbumPageItem fields.
		/// </summary>
		[RegisterProperty]
		public AlbumPageItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with AlbumPageItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class AlbumPageItemFields : AbstractHierarchicalObject<AlbumPageItemFields>
		{
			/// <summary>
			/// The content item of type AlbumPageItem that is a target of the extended API.
			/// </summary>
			private readonly AlbumPageItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="AlbumPageItemFields" /> class with the specified content item of type AlbumPageItem.
			/// </summary>
			/// <param name="instance">The content item of type AlbumPageItem that is a target of the extended API.</param>
			public AlbumPageItemFields(AlbumPageItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Album ID.
			/// </summary>
			public int AlbumID
			{
				get
				{
					return mInstance.AlbumID;
				}
				set
				{
					mInstance.AlbumID = value;
				}
			}


			/// <summary>
			/// Album Page Layout ID.
			/// </summary>
			public int AlbumPageLayoutID
			{
				get
				{
					return mInstance.AlbumPageLayoutID;
				}
				set
				{
					mInstance.AlbumPageLayoutID = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="AlbumPageItem" /> class.
		/// </summary>
		public AlbumPageItem() : base(CLASS_NAME)
		{
			mFields = new AlbumPageItemFields(this);
		}

		#endregion
	}
}