//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.Printforme;
using CMS.CustomTables;

[assembly: RegisterCustomTable(AlbumPhotoQueueItem.CLASS_NAME, typeof(AlbumPhotoQueueItem))]

namespace CMS.CustomTables.Types.Printforme
{
	/// <summary>
	/// Represents a content item of type AlbumPhotoQueueItem.
	/// </summary>
	public partial class AlbumPhotoQueueItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Printforme.AlbumPhotoQueue";


		/// <summary>
		/// The instance of the class that provides extended API for working with AlbumPhotoQueueItem fields.
		/// </summary>
		private readonly AlbumPhotoQueueItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Album ID.
		/// </summary>
		[DatabaseField]
		public int AlbumID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("AlbumID"), 0);
			}
			set
			{
				SetValue("AlbumID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// PhotoLocation.
		/// </summary>
		[DatabaseField]
		public string PhotoLocation
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PhotoLocation"), @"");
			}
			set
			{
				SetValue("PhotoLocation", value);
			}
		}


		/// <summary>
		/// IsPPIStatus.
		/// </summary>
		[DatabaseField]
		public bool IsPPIStatus
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("IsPPIStatus"), false);
			}
			set
			{
				SetValue("IsPPIStatus", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with AlbumPhotoQueueItem fields.
		/// </summary>
		[RegisterProperty]
		public AlbumPhotoQueueItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with AlbumPhotoQueueItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class AlbumPhotoQueueItemFields : AbstractHierarchicalObject<AlbumPhotoQueueItemFields>
		{
			/// <summary>
			/// The content item of type AlbumPhotoQueueItem that is a target of the extended API.
			/// </summary>
			private readonly AlbumPhotoQueueItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="AlbumPhotoQueueItemFields" /> class with the specified content item of type AlbumPhotoQueueItem.
			/// </summary>
			/// <param name="instance">The content item of type AlbumPhotoQueueItem that is a target of the extended API.</param>
			public AlbumPhotoQueueItemFields(AlbumPhotoQueueItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Album ID.
			/// </summary>
			public int AlbumID
			{
				get
				{
					return mInstance.AlbumID;
				}
				set
				{
					mInstance.AlbumID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}


			/// <summary>
			/// PhotoLocation.
			/// </summary>
			public string PhotoLocation
			{
				get
				{
					return mInstance.PhotoLocation;
				}
				set
				{
					mInstance.PhotoLocation = value;
				}
			}


			/// <summary>
			/// IsPPIStatus.
			/// </summary>
			public bool IsPPIStatus
			{
				get
				{
					return mInstance.IsPPIStatus;
				}
				set
				{
					mInstance.IsPPIStatus = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="AlbumPhotoQueueItem" /> class.
		/// </summary>
		public AlbumPhotoQueueItem() : base(CLASS_NAME)
		{
			mFields = new AlbumPhotoQueueItemFields(this);
		}

		#endregion
	}
}