//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.PrintForme;
using CMS.CustomTables;

[assembly: RegisterCustomTable(PaperMaterialsItem.CLASS_NAME, typeof(PaperMaterialsItem))]

namespace CMS.CustomTables.Types.PrintForme
{
	/// <summary>
	/// Represents a content item of type PaperMaterialsItem.
	/// </summary>
	public partial class PaperMaterialsItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "PrintForme.PaperMaterials";


		/// <summary>
		/// The instance of the class that provides extended API for working with PaperMaterialsItem fields.
		/// </summary>
		private readonly PaperMaterialsItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Page Type.
		/// </summary>
		[DatabaseField]
		public string PageType
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PageType"), @"");
			}
			set
			{
				SetValue("PageType", value);
			}
		}


		/// <summary>
		/// Availability.
		/// </summary>
		[DatabaseField]
		public bool Availability
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Availability"), true);
			}
			set
			{
				SetValue("Availability", value);
			}
		}


		/// <summary>
		/// Culture.
		/// </summary>
		[DatabaseField]
		public string Culture
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Culture"), @"");
			}
			set
			{
				SetValue("Culture", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with PaperMaterialsItem fields.
		/// </summary>
		[RegisterProperty]
		public PaperMaterialsItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with PaperMaterialsItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class PaperMaterialsItemFields : AbstractHierarchicalObject<PaperMaterialsItemFields>
		{
			/// <summary>
			/// The content item of type PaperMaterialsItem that is a target of the extended API.
			/// </summary>
			private readonly PaperMaterialsItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="PaperMaterialsItemFields" /> class with the specified content item of type PaperMaterialsItem.
			/// </summary>
			/// <param name="instance">The content item of type PaperMaterialsItem that is a target of the extended API.</param>
			public PaperMaterialsItemFields(PaperMaterialsItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Page Type.
			/// </summary>
			public string PageType
			{
				get
				{
					return mInstance.PageType;
				}
				set
				{
					mInstance.PageType = value;
				}
			}


			/// <summary>
			/// Availability.
			/// </summary>
			public bool Availability
			{
				get
				{
					return mInstance.Availability;
				}
				set
				{
					mInstance.Availability = value;
				}
			}


			/// <summary>
			/// Culture.
			/// </summary>
			public string Culture
			{
				get
				{
					return mInstance.Culture;
				}
				set
				{
					mInstance.Culture = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="PaperMaterialsItem" /> class.
		/// </summary>
		public PaperMaterialsItem() : base(CLASS_NAME)
		{
			mFields = new PaperMaterialsItemFields(this);
		}

		#endregion
	}
}