//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.PrintForme;
using CMS.CustomTables;

[assembly: RegisterCustomTable(PhotoProjectMasterItem.CLASS_NAME, typeof(PhotoProjectMasterItem))]

namespace CMS.CustomTables.Types.PrintForme
{
	/// <summary>
	/// Represents a content item of type PhotoProjectMasterItem.
	/// </summary>
	public partial class PhotoProjectMasterItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "PrintForme.PhotoProjectMaster";


		/// <summary>
		/// The instance of the class that provides extended API for working with PhotoProjectMasterItem fields.
		/// </summary>
		private readonly PhotoProjectMasterItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Service ID.
		/// </summary>
		[DatabaseField]
		public int ServiceID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ServiceID"), 0);
			}
			set
			{
				SetValue("ServiceID", value);
			}
		}


		/// <summary>
		/// UserID.
		/// </summary>
		[DatabaseField]
		public int UserID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("UserID"), 0);
			}
			set
			{
				SetValue("UserID", value);
			}
		}


		/// <summary>
		/// Project Date.
		/// </summary>
		[DatabaseField]
		public DateTime ProjectDate
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("ProjectDate"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("ProjectDate", value);
			}
		}


		/// <summary>
		/// PaperMaterialID.
		/// </summary>
		[DatabaseField]
		public int PaperMaterialID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PaperMaterialID"), 0);
			}
			set
			{
				SetValue("PaperMaterialID", value);
			}
		}


		/// <summary>
		/// IsComplete.
		/// </summary>
		[DatabaseField]
		public bool IsComplete1
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("IsComplete"), false);
			}
			set
			{
				SetValue("IsComplete", value);
			}
		}


		/// <summary>
		/// SKUID.
		/// </summary>
		[DatabaseField]
		public int SKUID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("SKUID"), 0);
			}
			set
			{
				SetValue("SKUID", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with PhotoProjectMasterItem fields.
		/// </summary>
		[RegisterProperty]
		public PhotoProjectMasterItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with PhotoProjectMasterItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class PhotoProjectMasterItemFields : AbstractHierarchicalObject<PhotoProjectMasterItemFields>
		{
			/// <summary>
			/// The content item of type PhotoProjectMasterItem that is a target of the extended API.
			/// </summary>
			private readonly PhotoProjectMasterItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="PhotoProjectMasterItemFields" /> class with the specified content item of type PhotoProjectMasterItem.
			/// </summary>
			/// <param name="instance">The content item of type PhotoProjectMasterItem that is a target of the extended API.</param>
			public PhotoProjectMasterItemFields(PhotoProjectMasterItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Service ID.
			/// </summary>
			public int ServiceID
			{
				get
				{
					return mInstance.ServiceID;
				}
				set
				{
					mInstance.ServiceID = value;
				}
			}


			/// <summary>
			/// UserID.
			/// </summary>
			public int UserID
			{
				get
				{
					return mInstance.UserID;
				}
				set
				{
					mInstance.UserID = value;
				}
			}


			/// <summary>
			/// Project Date.
			/// </summary>
			public DateTime ProjectDate
			{
				get
				{
					return mInstance.ProjectDate;
				}
				set
				{
					mInstance.ProjectDate = value;
				}
			}


			/// <summary>
			/// PaperMaterialID.
			/// </summary>
			public int PaperMaterialID
			{
				get
				{
					return mInstance.PaperMaterialID;
				}
				set
				{
					mInstance.PaperMaterialID = value;
				}
			}


			/// <summary>
			/// IsComplete.
			/// </summary>
			public bool IsComplete
			{
				get
				{
					return mInstance.IsComplete1;
				}
				set
				{
					mInstance.IsComplete1 = value;
				}
			}


			/// <summary>
			/// SKUID.
			/// </summary>
			public int SKUID
			{
				get
				{
					return mInstance.SKUID;
				}
				set
				{
					mInstance.SKUID = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="PhotoProjectMasterItem" /> class.
		/// </summary>
		public PhotoProjectMasterItem() : base(CLASS_NAME)
		{
			mFields = new PhotoProjectMasterItemFields(this);
		}

		#endregion
	}
}