//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.PrintForme;
using CMS.CustomTables;

[assembly: RegisterCustomTable(ServiceSettingsItem.CLASS_NAME, typeof(ServiceSettingsItem))]

namespace CMS.CustomTables.Types.PrintForme
{
	/// <summary>
	/// Represents a content item of type ServiceSettingsItem.
	/// </summary>
	public partial class ServiceSettingsItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "PrintForme.ServiceSettings";


		/// <summary>
		/// The instance of the class that provides extended API for working with ServiceSettingsItem fields.
		/// </summary>
		private readonly ServiceSettingsItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Code.
		/// </summary>
		[DatabaseField]
		public string Code
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Code"), @"Code");
			}
			set
			{
				SetValue("Code", value);
			}
		}


		/// <summary>
		/// Description.
		/// </summary>
		[DatabaseField]
		public string Description
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Description"), @"");
			}
			set
			{
				SetValue("Description", value);
			}
		}


		/// <summary>
		/// Price.
		/// </summary>
		[DatabaseField]
		public string Price
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Price"), @"");
			}
			set
			{
				SetValue("Price", value);
			}
		}


		/// <summary>
		/// Availability .
		/// </summary>
		[DatabaseField]
		public bool Availability
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Availability"), false);
			}
			set
			{
				SetValue("Availability", value);
			}
		}


		/// <summary>
		/// ServiceID.
		/// </summary>
		[DatabaseField]
		public int ServiceID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ServiceID"), 0);
			}
			set
			{
				SetValue("ServiceID", value);
			}
		}


		/// <summary>
		/// Height.
		/// </summary>
		[DatabaseField]
		public int Height
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("Height"), 0);
			}
			set
			{
				SetValue("Height", value);
			}
		}


		/// <summary>
		/// Width.
		/// </summary>
		[DatabaseField]
		public int Width
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("Width"), 0);
			}
			set
			{
				SetValue("Width", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ServiceSettingsItem fields.
		/// </summary>
		[RegisterProperty]
		public ServiceSettingsItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ServiceSettingsItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ServiceSettingsItemFields : AbstractHierarchicalObject<ServiceSettingsItemFields>
		{
			/// <summary>
			/// The content item of type ServiceSettingsItem that is a target of the extended API.
			/// </summary>
			private readonly ServiceSettingsItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ServiceSettingsItemFields" /> class with the specified content item of type ServiceSettingsItem.
			/// </summary>
			/// <param name="instance">The content item of type ServiceSettingsItem that is a target of the extended API.</param>
			public ServiceSettingsItemFields(ServiceSettingsItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Code.
			/// </summary>
			public string Code
			{
				get
				{
					return mInstance.Code;
				}
				set
				{
					mInstance.Code = value;
				}
			}


			/// <summary>
			/// Description.
			/// </summary>
			public string Description
			{
				get
				{
					return mInstance.Description;
				}
				set
				{
					mInstance.Description = value;
				}
			}


			/// <summary>
			/// Price.
			/// </summary>
			public string Price
			{
				get
				{
					return mInstance.Price;
				}
				set
				{
					mInstance.Price = value;
				}
			}


			/// <summary>
			/// Availability .
			/// </summary>
			public bool Availability
			{
				get
				{
					return mInstance.Availability;
				}
				set
				{
					mInstance.Availability = value;
				}
			}


			/// <summary>
			/// ServiceID.
			/// </summary>
			public int ServiceID
			{
				get
				{
					return mInstance.ServiceID;
				}
				set
				{
					mInstance.ServiceID = value;
				}
			}


			/// <summary>
			/// Height.
			/// </summary>
			public int Height
			{
				get
				{
					return mInstance.Height;
				}
				set
				{
					mInstance.Height = value;
				}
			}


			/// <summary>
			/// Width.
			/// </summary>
			public int Width
			{
				get
				{
					return mInstance.Width;
				}
				set
				{
					mInstance.Width = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ServiceSettingsItem" /> class.
		/// </summary>
		public ServiceSettingsItem() : base(CLASS_NAME)
		{
			mFields = new ServiceSettingsItemFields(this);
		}

		#endregion
	}
}