//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.PrintForme;
using CMS.CustomTables;

[assembly: RegisterCustomTable(WallPrintingProjectMasterItem.CLASS_NAME, typeof(WallPrintingProjectMasterItem))]

namespace CMS.CustomTables.Types.PrintForme
{
	/// <summary>
	/// Represents a content item of type WallPrintingProjectMasterItem.
	/// </summary>
	public partial class WallPrintingProjectMasterItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "PrintForme.WallPrintingProjectMaster";


		/// <summary>
		/// The instance of the class that provides extended API for working with WallPrintingProjectMasterItem fields.
		/// </summary>
		private readonly WallPrintingProjectMasterItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// UserID.
		/// </summary>
		[DatabaseField]
		public int UserID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("UserID"), 0);
			}
			set
			{
				SetValue("UserID", value);
			}
		}


		/// <summary>
		/// ProjectDate.
		/// </summary>
		[DatabaseField]
		public DateTime ProjectDate
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("ProjectDate"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("ProjectDate", value);
			}
		}


		/// <summary>
		/// PaperMaterialID.
		/// </summary>
		[DatabaseField]
		public int PaperMaterialID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PaperMaterialID"), 0);
			}
			set
			{
				SetValue("PaperMaterialID", value);
			}
		}


		/// <summary>
		/// FrameColorID.
		/// </summary>
		[DatabaseField]
		public int FrameColorID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("FrameColorID"), 0);
			}
			set
			{
				SetValue("FrameColorID", value);
			}
		}


		/// <summary>
		/// PaintingSize.
		/// </summary>
		[DatabaseField]
		public string PaintingSize
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PaintingSize"), @"");
			}
			set
			{
				SetValue("PaintingSize", value);
			}
		}


		/// <summary>
		/// IsComplete.
		/// </summary>
		[DatabaseField]
		public bool IsComplete1
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("IsComplete"), false);
			}
			set
			{
				SetValue("IsComplete", value);
			}
		}


		/// <summary>
		/// SKUID.
		/// </summary>
		[DatabaseField]
		public int SKUID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("SKUID"), 0);
			}
			set
			{
				SetValue("SKUID", value);
			}
		}


		/// <summary>
		/// ServiceID.
		/// </summary>
		[DatabaseField]
		public int ServiceID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ServiceID"), 0);
			}
			set
			{
				SetValue("ServiceID", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with WallPrintingProjectMasterItem fields.
		/// </summary>
		[RegisterProperty]
		public WallPrintingProjectMasterItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with WallPrintingProjectMasterItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class WallPrintingProjectMasterItemFields : AbstractHierarchicalObject<WallPrintingProjectMasterItemFields>
		{
			/// <summary>
			/// The content item of type WallPrintingProjectMasterItem that is a target of the extended API.
			/// </summary>
			private readonly WallPrintingProjectMasterItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="WallPrintingProjectMasterItemFields" /> class with the specified content item of type WallPrintingProjectMasterItem.
			/// </summary>
			/// <param name="instance">The content item of type WallPrintingProjectMasterItem that is a target of the extended API.</param>
			public WallPrintingProjectMasterItemFields(WallPrintingProjectMasterItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// UserID.
			/// </summary>
			public int UserID
			{
				get
				{
					return mInstance.UserID;
				}
				set
				{
					mInstance.UserID = value;
				}
			}


			/// <summary>
			/// ProjectDate.
			/// </summary>
			public DateTime ProjectDate
			{
				get
				{
					return mInstance.ProjectDate;
				}
				set
				{
					mInstance.ProjectDate = value;
				}
			}


			/// <summary>
			/// PaperMaterialID.
			/// </summary>
			public int PaperMaterialID
			{
				get
				{
					return mInstance.PaperMaterialID;
				}
				set
				{
					mInstance.PaperMaterialID = value;
				}
			}


			/// <summary>
			/// FrameColorID.
			/// </summary>
			public int FrameColorID
			{
				get
				{
					return mInstance.FrameColorID;
				}
				set
				{
					mInstance.FrameColorID = value;
				}
			}


			/// <summary>
			/// PaintingSize.
			/// </summary>
			public string PaintingSize
			{
				get
				{
					return mInstance.PaintingSize;
				}
				set
				{
					mInstance.PaintingSize = value;
				}
			}


			/// <summary>
			/// IsComplete.
			/// </summary>
			public bool IsComplete
			{
				get
				{
					return mInstance.IsComplete1;
				}
				set
				{
					mInstance.IsComplete1 = value;
				}
			}


			/// <summary>
			/// SKUID.
			/// </summary>
			public int SKUID
			{
				get
				{
					return mInstance.SKUID;
				}
				set
				{
					mInstance.SKUID = value;
				}
			}


			/// <summary>
			/// ServiceID.
			/// </summary>
			public int ServiceID
			{
				get
				{
					return mInstance.ServiceID;
				}
				set
				{
					mInstance.ServiceID = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="WallPrintingProjectMasterItem" /> class.
		/// </summary>
		public WallPrintingProjectMasterItem() : base(CLASS_NAME)
		{
			mFields = new WallPrintingProjectMasterItemFields(this);
		}

		#endregion
	}
}