//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.PrintForme;
using CMS.CustomTables;

[assembly: RegisterCustomTable(WoodenPalletsMasterItem.CLASS_NAME, typeof(WoodenPalletsMasterItem))]

namespace CMS.CustomTables.Types.PrintForme
{
	/// <summary>
	/// Represents a content item of type WoodenPalletsMasterItem.
	/// </summary>
	public partial class WoodenPalletsMasterItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "PrintForme.WoodenPalletsMaster";


		/// <summary>
		/// The instance of the class that provides extended API for working with WoodenPalletsMasterItem fields.
		/// </summary>
		private readonly WoodenPalletsMasterItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// UserID.
		/// </summary>
		[DatabaseField]
		public int UserID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("UserID"), 0);
			}
			set
			{
				SetValue("UserID", value);
			}
		}


		/// <summary>
		/// ProjectDate.
		/// </summary>
		[DatabaseField]
		public DateTime ProjectDate
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("ProjectDate"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("ProjectDate", value);
			}
		}


		/// <summary>
		/// PlankThickness.
		/// </summary>
		[DatabaseField]
		public string PlankThickness
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PlankThickness"), @"");
			}
			set
			{
				SetValue("PlankThickness", value);
			}
		}


		/// <summary>
		/// IsComplete.
		/// </summary>
		[DatabaseField]
		public bool IsComplete1
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("IsComplete"), false);
			}
			set
			{
				SetValue("IsComplete", value);
			}
		}


		/// <summary>
		/// SKUID.
		/// </summary>
		[DatabaseField]
		public int SKUID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("SKUID"), 0);
			}
			set
			{
				SetValue("SKUID", value);
			}
		}


		/// <summary>
		/// ServiceID.
		/// </summary>
		[DatabaseField]
		public int ServiceID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ServiceID"), 0);
			}
			set
			{
				SetValue("ServiceID", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with WoodenPalletsMasterItem fields.
		/// </summary>
		[RegisterProperty]
		public WoodenPalletsMasterItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with WoodenPalletsMasterItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class WoodenPalletsMasterItemFields : AbstractHierarchicalObject<WoodenPalletsMasterItemFields>
		{
			/// <summary>
			/// The content item of type WoodenPalletsMasterItem that is a target of the extended API.
			/// </summary>
			private readonly WoodenPalletsMasterItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="WoodenPalletsMasterItemFields" /> class with the specified content item of type WoodenPalletsMasterItem.
			/// </summary>
			/// <param name="instance">The content item of type WoodenPalletsMasterItem that is a target of the extended API.</param>
			public WoodenPalletsMasterItemFields(WoodenPalletsMasterItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// UserID.
			/// </summary>
			public int UserID
			{
				get
				{
					return mInstance.UserID;
				}
				set
				{
					mInstance.UserID = value;
				}
			}


			/// <summary>
			/// ProjectDate.
			/// </summary>
			public DateTime ProjectDate
			{
				get
				{
					return mInstance.ProjectDate;
				}
				set
				{
					mInstance.ProjectDate = value;
				}
			}


			/// <summary>
			/// PlankThickness.
			/// </summary>
			public string PlankThickness
			{
				get
				{
					return mInstance.PlankThickness;
				}
				set
				{
					mInstance.PlankThickness = value;
				}
			}


			/// <summary>
			/// IsComplete.
			/// </summary>
			public bool IsComplete
			{
				get
				{
					return mInstance.IsComplete1;
				}
				set
				{
					mInstance.IsComplete1 = value;
				}
			}


			/// <summary>
			/// SKUID.
			/// </summary>
			public int SKUID
			{
				get
				{
					return mInstance.SKUID;
				}
				set
				{
					mInstance.SKUID = value;
				}
			}


			/// <summary>
			/// ServiceID.
			/// </summary>
			public int ServiceID
			{
				get
				{
					return mInstance.ServiceID;
				}
				set
				{
					mInstance.ServiceID = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="WoodenPalletsMasterItem" /> class.
		/// </summary>
		public WoodenPalletsMasterItem() : base(CLASS_NAME)
		{
			mFields = new WoodenPalletsMasterItemFields(this);
		}

		#endregion
	}
}