//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.PrintForme;
using CMS.CustomTables;

[assembly: RegisterCustomTable(WoodenPalletsDetailItem.CLASS_NAME, typeof(WoodenPalletsDetailItem))]

namespace CMS.CustomTables.Types.PrintForme
{
	/// <summary>
	/// Represents a content item of type WoodenPalletsDetailItem.
	/// </summary>
	public partial class WoodenPalletsDetailItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "PrintForme.WoodenPalletsDetail";


		/// <summary>
		/// The instance of the class that provides extended API for working with WoodenPalletsDetailItem fields.
		/// </summary>
		private readonly WoodenPalletsDetailItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ProjectID.
		/// </summary>
		[DatabaseField]
		public int ProjectID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ProjectID"), 0);
			}
			set
			{
				SetValue("ProjectID", value);
			}
		}


		/// <summary>
		/// ImageUrl.
		/// </summary>
		[DatabaseField]
		public string ImageUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ImageUrl"), @"");
			}
			set
			{
				SetValue("ImageUrl", value);
			}
		}


		/// <summary>
		/// NoOfCopy.
		/// </summary>
		[DatabaseField]
		public int NoOfCopy
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("NoOfCopy"), 0);
			}
			set
			{
				SetValue("NoOfCopy", value);
			}
		}


		/// <summary>
		/// ImageSizeID.
		/// </summary>
		[DatabaseField]
		public int ImageSizeID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ImageSizeID"), 0);
			}
			set
			{
				SetValue("ImageSizeID", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with WoodenPalletsDetailItem fields.
		/// </summary>
		[RegisterProperty]
		public WoodenPalletsDetailItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with WoodenPalletsDetailItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class WoodenPalletsDetailItemFields : AbstractHierarchicalObject<WoodenPalletsDetailItemFields>
		{
			/// <summary>
			/// The content item of type WoodenPalletsDetailItem that is a target of the extended API.
			/// </summary>
			private readonly WoodenPalletsDetailItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="WoodenPalletsDetailItemFields" /> class with the specified content item of type WoodenPalletsDetailItem.
			/// </summary>
			/// <param name="instance">The content item of type WoodenPalletsDetailItem that is a target of the extended API.</param>
			public WoodenPalletsDetailItemFields(WoodenPalletsDetailItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ProjectID.
			/// </summary>
			public int ProjectID
			{
				get
				{
					return mInstance.ProjectID;
				}
				set
				{
					mInstance.ProjectID = value;
				}
			}


			/// <summary>
			/// ImageUrl.
			/// </summary>
			public string ImageUrl
			{
				get
				{
					return mInstance.ImageUrl;
				}
				set
				{
					mInstance.ImageUrl = value;
				}
			}


			/// <summary>
			/// NoOfCopy.
			/// </summary>
			public int NoOfCopy
			{
				get
				{
					return mInstance.NoOfCopy;
				}
				set
				{
					mInstance.NoOfCopy = value;
				}
			}


			/// <summary>
			/// ImageSizeID.
			/// </summary>
			public int ImageSizeID
			{
				get
				{
					return mInstance.ImageSizeID;
				}
				set
				{
					mInstance.ImageSizeID = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="WoodenPalletsDetailItem" /> class.
		/// </summary>
		public WoodenPalletsDetailItem() : base(CLASS_NAME)
		{
			mFields = new WoodenPalletsDetailItemFields(this);
		}

		#endregion
	}
}