//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.PrintForMe;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(DeleteAlbumContainer.CLASS_NAME, typeof(DeleteAlbumContainer))]

namespace CMS.DocumentEngine.Types.PrintForMe
{
	/// <summary>
	/// Represents a content item of type DeleteAlbumContainer.
	/// </summary>
	public partial class DeleteAlbumContainer : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "PrintForMe.DeleteAlbumContainer";


		/// <summary>
		/// The instance of the class that provides extended API for working with DeleteAlbumContainer fields.
		/// </summary>
		private readonly DeleteAlbumContainerFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Gets an object that provides extended API for working with DeleteAlbumContainer fields.
		/// </summary>
		[RegisterProperty]
		public DeleteAlbumContainerFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with DeleteAlbumContainer fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class DeleteAlbumContainerFields : AbstractHierarchicalObject<DeleteAlbumContainerFields>
		{
			/// <summary>
			/// The content item of type DeleteAlbumContainer that is a target of the extended API.
			/// </summary>
			private readonly DeleteAlbumContainer mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="DeleteAlbumContainerFields" /> class with the specified content item of type DeleteAlbumContainer.
			/// </summary>
			/// <param name="instance">The content item of type DeleteAlbumContainer that is a target of the extended API.</param>
			public DeleteAlbumContainerFields(DeleteAlbumContainer instance)
			{
				mInstance = instance;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="DeleteAlbumContainer" /> class.
		/// </summary>
		public DeleteAlbumContainer() : base(CLASS_NAME)
		{
			mFields = new DeleteAlbumContainerFields(this);
		}

		#endregion
	}
}