//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.PrintForMe;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(FooterItem.CLASS_NAME, typeof(FooterItem))]

namespace CMS.DocumentEngine.Types.PrintForMe
{
	/// <summary>
	/// Represents a content item of type FooterItem.
	/// </summary>
	public partial class FooterItem : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "PrintForMe.FooterItem";


		/// <summary>
		/// The instance of the class that provides extended API for working with FooterItem fields.
		/// </summary>
		private readonly FooterItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// FooterItemID.
		/// </summary>
		[DatabaseIDField]
		public int FooterItemID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("FooterItemID"), 0);
			}
			set
			{
				SetValue("FooterItemID", value);
			}
		}


		/// <summary>
		/// LinkText.
		/// </summary>
		[DatabaseField]
		public string LinkText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkText"), @"");
			}
			set
			{
				SetValue("LinkText", value);
			}
		}


		/// <summary>
		/// Url.
		/// </summary>
		[DatabaseField]
		public string Url
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Url"), @"");
			}
			set
			{
				SetValue("Url", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with FooterItem fields.
		/// </summary>
		[RegisterProperty]
		public FooterItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with FooterItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class FooterItemFields : AbstractHierarchicalObject<FooterItemFields>
		{
			/// <summary>
			/// The content item of type FooterItem that is a target of the extended API.
			/// </summary>
			private readonly FooterItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="FooterItemFields" /> class with the specified content item of type FooterItem.
			/// </summary>
			/// <param name="instance">The content item of type FooterItem that is a target of the extended API.</param>
			public FooterItemFields(FooterItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// FooterItemID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.FooterItemID;
				}
				set
				{
					mInstance.FooterItemID = value;
				}
			}


			/// <summary>
			/// LinkText.
			/// </summary>
			public string LinkText
			{
				get
				{
					return mInstance.LinkText;
				}
				set
				{
					mInstance.LinkText = value;
				}
			}


			/// <summary>
			/// Url.
			/// </summary>
			public string Url
			{
				get
				{
					return mInstance.Url;
				}
				set
				{
					mInstance.Url = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="FooterItem" /> class.
		/// </summary>
		public FooterItem() : base(CLASS_NAME)
		{
			mFields = new FooterItemFields(this);
		}

		#endregion
	}
}