//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.PrintForMe;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(FooterSection.CLASS_NAME, typeof(FooterSection))]

namespace CMS.DocumentEngine.Types.PrintForMe
{
	/// <summary>
	/// Represents a content item of type FooterSection.
	/// </summary>
	public partial class FooterSection : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "PrintForMe.FooterSection";


		/// <summary>
		/// The instance of the class that provides extended API for working with FooterSection fields.
		/// </summary>
		private readonly FooterSectionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// FooterSectionID.
		/// </summary>
		[DatabaseIDField]
		public int FooterSectionID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("FooterSectionID"), 0);
			}
			set
			{
				SetValue("FooterSectionID", value);
			}
		}


		/// <summary>
		/// Section Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with FooterSection fields.
		/// </summary>
		[RegisterProperty]
		public FooterSectionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with FooterSection fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class FooterSectionFields : AbstractHierarchicalObject<FooterSectionFields>
		{
			/// <summary>
			/// The content item of type FooterSection that is a target of the extended API.
			/// </summary>
			private readonly FooterSection mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="FooterSectionFields" /> class with the specified content item of type FooterSection.
			/// </summary>
			/// <param name="instance">The content item of type FooterSection that is a target of the extended API.</param>
			public FooterSectionFields(FooterSection instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// FooterSectionID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.FooterSectionID;
				}
				set
				{
					mInstance.FooterSectionID = value;
				}
			}


			/// <summary>
			/// Section Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="FooterSection" /> class.
		/// </summary>
		public FooterSection() : base(CLASS_NAME)
		{
			mFields = new FooterSectionFields(this);
		}

		#endregion
	}
}