//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.PrintForMe;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(PrintingServices.CLASS_NAME, typeof(PrintingServices))]

namespace CMS.DocumentEngine.Types.PrintForMe
{
	/// <summary>
	/// Represents a content item of type PrintingServices.
	/// </summary>
	public partial class PrintingServices : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "PrintForMe.PrintingServices";


		/// <summary>
		/// The instance of the class that provides extended API for working with PrintingServices fields.
		/// </summary>
		private readonly PrintingServicesFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// PrintingServicesID.
		/// </summary>
		[DatabaseIDField]
		public int PrintingServicesID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PrintingServicesID"), 0);
			}
			set
			{
				SetValue("PrintingServicesID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Iamge.
		/// </summary>
		[DatabaseField]
		public string Image
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Image"), @"");
			}
			set
			{
				SetValue("Image", value);
			}
		}


		/// <summary>
		/// Link.
		/// </summary>
		[DatabaseField]
		public string Link
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Link"), @"");
			}
			set
			{
				SetValue("Link", value);
			}
		}


		/// <summary>
		/// Color Code.
		/// </summary>
		[DatabaseField]
		public string ColorCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ColorCode"), @"");
			}
			set
			{
				SetValue("ColorCode", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with PrintingServices fields.
		/// </summary>
		[RegisterProperty]
		public PrintingServicesFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with PrintingServices fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class PrintingServicesFields : AbstractHierarchicalObject<PrintingServicesFields>
		{
			/// <summary>
			/// The content item of type PrintingServices that is a target of the extended API.
			/// </summary>
			private readonly PrintingServices mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="PrintingServicesFields" /> class with the specified content item of type PrintingServices.
			/// </summary>
			/// <param name="instance">The content item of type PrintingServices that is a target of the extended API.</param>
			public PrintingServicesFields(PrintingServices instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// PrintingServicesID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.PrintingServicesID;
				}
				set
				{
					mInstance.PrintingServicesID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}


			/// <summary>
			/// Iamge.
			/// </summary>
			public string Image
			{
				get
				{
					return mInstance.Image;
				}
				set
				{
					mInstance.Image = value;
				}
			}


			/// <summary>
			/// Link.
			/// </summary>
			public string Link
			{
				get
				{
					return mInstance.Link;
				}
				set
				{
					mInstance.Link = value;
				}
			}


			/// <summary>
			/// Color Code.
			/// </summary>
			public string ColorCode
			{
				get
				{
					return mInstance.ColorCode;
				}
				set
				{
					mInstance.ColorCode = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="PrintingServices" /> class.
		/// </summary>
		public PrintingServices() : base(CLASS_NAME)
		{
			mFields = new PrintingServicesFields(this);
		}

		#endregion
	}
}