//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.PrintForMe;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(ProductSectionType.CLASS_NAME, typeof(ProductSectionType))]

namespace CMS.DocumentEngine.Types.PrintForMe
{
	/// <summary>
	/// Represents a content item of type ProductSectionType.
	/// </summary>
	public partial class ProductSectionType : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "PrintForMe.ProductSectionType";


		/// <summary>
		/// The instance of the class that provides extended API for working with ProductSectionType fields.
		/// </summary>
		private readonly ProductSectionTypeFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ProductSectionTypeID.
		/// </summary>
		[DatabaseIDField]
		public int ProductSectionTypeID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ProductSectionTypeID"), 0);
			}
			set
			{
				SetValue("ProductSectionTypeID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ProductSectionType fields.
		/// </summary>
		[RegisterProperty]
		public ProductSectionTypeFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ProductSectionType fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ProductSectionTypeFields : AbstractHierarchicalObject<ProductSectionTypeFields>
		{
			/// <summary>
			/// The content item of type ProductSectionType that is a target of the extended API.
			/// </summary>
			private readonly ProductSectionType mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ProductSectionTypeFields" /> class with the specified content item of type ProductSectionType.
			/// </summary>
			/// <param name="instance">The content item of type ProductSectionType that is a target of the extended API.</param>
			public ProductSectionTypeFields(ProductSectionType instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ProductSectionTypeID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ProductSectionTypeID;
				}
				set
				{
					mInstance.ProductSectionTypeID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ProductSectionType" /> class.
		/// </summary>
		public ProductSectionType() : base(CLASS_NAME)
		{
			mFields = new ProductSectionTypeFields(this);
		}

		#endregion
	}
}