//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.PrintForMe;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Products.CLASS_NAME, typeof(Products))]

namespace CMS.DocumentEngine.Types.PrintForMe
{
	/// <summary>
	/// Represents a content item of type Products.
	/// </summary>
	public partial class Products : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "PrintForMe.Products";


		/// <summary>
		/// The instance of the class that provides extended API for working with Products fields.
		/// </summary>
		private readonly ProductsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ProductsID.
		/// </summary>
		[DatabaseIDField]
		public int ProductsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ProductsID"), 0);
			}
			set
			{
				SetValue("ProductsID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Products fields.
		/// </summary>
		[RegisterProperty]
		public ProductsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Products fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ProductsFields : AbstractHierarchicalObject<ProductsFields>
		{
			/// <summary>
			/// The content item of type Products that is a target of the extended API.
			/// </summary>
			private readonly Products mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ProductsFields" /> class with the specified content item of type Products.
			/// </summary>
			/// <param name="instance">The content item of type Products that is a target of the extended API.</param>
			public ProductsFields(Products instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ProductsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ProductsID;
				}
				set
				{
					mInstance.ProductsID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Products" /> class.
		/// </summary>
		public Products() : base(CLASS_NAME)
		{
			mFields = new ProductsFields(this);
		}

		#endregion
	}
}