//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.PrintForMe;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(QA.CLASS_NAME, typeof(QA))]

namespace CMS.DocumentEngine.Types.PrintForMe
{
	/// <summary>
	/// Represents a content item of type QA.
	/// </summary>
	public partial class QA : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "PrintForMe.QA";


		/// <summary>
		/// The instance of the class that provides extended API for working with QA fields.
		/// </summary>
		private readonly QAFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// QAID.
		/// </summary>
		[DatabaseIDField]
		public int QAID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("QAID"), 0);
			}
			set
			{
				SetValue("QAID", value);
			}
		}


		/// <summary>
		/// Question.
		/// </summary>
		[DatabaseField]
		public string Question
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Question"), @"");
			}
			set
			{
				SetValue("Question", value);
			}
		}


		/// <summary>
		/// Answer.
		/// </summary>
		[DatabaseField]
		public string Answer
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Answer"), @"");
			}
			set
			{
				SetValue("Answer", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with QA fields.
		/// </summary>
		[RegisterProperty]
		public QAFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with QA fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class QAFields : AbstractHierarchicalObject<QAFields>
		{
			/// <summary>
			/// The content item of type QA that is a target of the extended API.
			/// </summary>
			private readonly QA mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="QAFields" /> class with the specified content item of type QA.
			/// </summary>
			/// <param name="instance">The content item of type QA that is a target of the extended API.</param>
			public QAFields(QA instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// QAID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.QAID;
				}
				set
				{
					mInstance.QAID = value;
				}
			}


			/// <summary>
			/// Question.
			/// </summary>
			public string Question
			{
				get
				{
					return mInstance.Question;
				}
				set
				{
					mInstance.Question = value;
				}
			}


			/// <summary>
			/// Answer.
			/// </summary>
			public string Answer
			{
				get
				{
					return mInstance.Answer;
				}
				set
				{
					mInstance.Answer = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="QA" /> class.
		/// </summary>
		public QA() : base(CLASS_NAME)
		{
			mFields = new QAFields(this);
		}

		#endregion
	}
}