//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.PrintForMe;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(QAs.CLASS_NAME, typeof(QAs))]

namespace CMS.DocumentEngine.Types.PrintForMe
{
	/// <summary>
	/// Represents a content item of type QAs.
	/// </summary>
	public partial class QAs : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "PrintForMe.QAs";


		/// <summary>
		/// The instance of the class that provides extended API for working with QAs fields.
		/// </summary>
		private readonly QAsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// QAsID.
		/// </summary>
		[DatabaseIDField]
		public int QAsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("QAsID"), 0);
			}
			set
			{
				SetValue("QAsID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with QAs fields.
		/// </summary>
		[RegisterProperty]
		public QAsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with QAs fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class QAsFields : AbstractHierarchicalObject<QAsFields>
		{
			/// <summary>
			/// The content item of type QAs that is a target of the extended API.
			/// </summary>
			private readonly QAs mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="QAsFields" /> class with the specified content item of type QAs.
			/// </summary>
			/// <param name="instance">The content item of type QAs that is a target of the extended API.</param>
			public QAsFields(QAs instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// QAsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.QAsID;
				}
				set
				{
					mInstance.QAsID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="QAs" /> class.
		/// </summary>
		public QAs() : base(CLASS_NAME)
		{
			mFields = new QAsFields(this);
		}

		#endregion
	}
}