//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.PrintForMe;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(StoreInfo.CLASS_NAME, typeof(StoreInfo))]

namespace CMS.DocumentEngine.Types.PrintForMe
{
	/// <summary>
	/// Represents a content item of type StoreInfo.
	/// </summary>
	public partial class StoreInfo : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "PrintForMe.StoreInfo";


		/// <summary>
		/// The instance of the class that provides extended API for working with StoreInfo fields.
		/// </summary>
		private readonly StoreInfoFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// StoreInfoID.
		/// </summary>
		[DatabaseIDField]
		public int StoreInfoID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("StoreInfoID"), 0);
			}
			set
			{
				SetValue("StoreInfoID", value);
			}
		}


		/// <summary>
		/// Site Name.
		/// </summary>
		[DatabaseField]
		public string SiteName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SiteName"), @"");
			}
			set
			{
				SetValue("SiteName", value);
			}
		}


		/// <summary>
		/// SiteID.
		/// </summary>
		[DatabaseField]
		public string SiteID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SiteID"), @"");
			}
			set
			{
				SetValue("SiteID", value);
			}
		}


		/// <summary>
		/// Logo.
		/// </summary>
		[DatabaseField]
		public string SiteLogo
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SiteLogo"), @"");
			}
			set
			{
				SetValue("SiteLogo", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with StoreInfo fields.
		/// </summary>
		[RegisterProperty]
		public StoreInfoFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with StoreInfo fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class StoreInfoFields : AbstractHierarchicalObject<StoreInfoFields>
		{
			/// <summary>
			/// The content item of type StoreInfo that is a target of the extended API.
			/// </summary>
			private readonly StoreInfo mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="StoreInfoFields" /> class with the specified content item of type StoreInfo.
			/// </summary>
			/// <param name="instance">The content item of type StoreInfo that is a target of the extended API.</param>
			public StoreInfoFields(StoreInfo instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// StoreInfoID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.StoreInfoID;
				}
				set
				{
					mInstance.StoreInfoID = value;
				}
			}


			/// <summary>
			/// Site Name.
			/// </summary>
			public string SiteName
			{
				get
				{
					return mInstance.SiteName;
				}
				set
				{
					mInstance.SiteName = value;
				}
			}


			/// <summary>
			/// SiteID.
			/// </summary>
			public string SiteID
			{
				get
				{
					return mInstance.SiteID;
				}
				set
				{
					mInstance.SiteID = value;
				}
			}


			/// <summary>
			/// Logo.
			/// </summary>
			public string SiteLogo
			{
				get
				{
					return mInstance.SiteLogo;
				}
				set
				{
					mInstance.SiteLogo = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="StoreInfo" /> class.
		/// </summary>
		public StoreInfo() : base(CLASS_NAME)
		{
			mFields = new StoreInfoFields(this);
		}

		#endregion
	}
}