//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.OnlineForms.Types;
using CMS.OnlineForms;

[assembly: RegisterBizForm(ContactUsItem.CLASS_NAME, typeof(ContactUsItem))]

namespace CMS.OnlineForms.Types
{
	/// <summary>
	/// Represents a content item of type ContactUsItem.
	/// </summary>
	public partial class ContactUsItem : BizFormItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BizForm.ContactUs";


		/// <summary>
		/// The instance of the class that provides extended API for working with ContactUsItem fields.
		/// </summary>
		private readonly ContactUsItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Email.
		/// </summary>
		[DatabaseField]
		public string Email
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Email"), @"");
			}
			set
			{
				SetValue("Email", value);
			}
		}


		/// <summary>
		/// Purpose.
		/// </summary>
		[DatabaseField]
		public string Purpose
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Purpose"), @"");
			}
			set
			{
				SetValue("Purpose", value);
			}
		}


		/// <summary>
		/// Message.
		/// </summary>
		[DatabaseField]
		public string Message
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Message"), @"");
			}
			set
			{
				SetValue("Message", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ContactUsItem fields.
		/// </summary>
		[RegisterProperty]
		public ContactUsItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ContactUsItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ContactUsItemFields : AbstractHierarchicalObject<ContactUsItemFields>
		{
			/// <summary>
			/// The content item of type ContactUsItem that is a target of the extended API.
			/// </summary>
			private readonly ContactUsItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ContactUsItemFields" /> class with the specified content item of type ContactUsItem.
			/// </summary>
			/// <param name="instance">The content item of type ContactUsItem that is a target of the extended API.</param>
			public ContactUsItemFields(ContactUsItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}


			/// <summary>
			/// Email.
			/// </summary>
			public string Email
			{
				get
				{
					return mInstance.Email;
				}
				set
				{
					mInstance.Email = value;
				}
			}


			/// <summary>
			/// Purpose.
			/// </summary>
			public string Purpose
			{
				get
				{
					return mInstance.Purpose;
				}
				set
				{
					mInstance.Purpose = value;
				}
			}


			/// <summary>
			/// Message.
			/// </summary>
			public string Message
			{
				get
				{
					return mInstance.Message;
				}
				set
				{
					mInstance.Message = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ContactUsItem" /> class.
		/// </summary>
		public ContactUsItem() : base(CLASS_NAME)
		{
			mFields = new ContactUsItemFields(this);
		}

		#endregion
	}
}